# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b766fccc47c83ed232a209e56f7dec83356c0602a2df92631684bdf2263c102e496f1156f58bdc3c6f02117f9bc0d7368676b1c44acf19739761e9de53f788ac

test:
  secret_key_base: b87ecc07fe902234fa14bfff4f04d5b7dd41dd2442efff712d43550386f95aa45beeaae4f624c785867de6b85220d75163ea33d3fa087c7883d5dd8d03a7ed4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
